---
- name: This playbook installs Apache and copies a file
  hosts: metro
  become: true
  tasks:
    - name: Installing httpd package on RedHat
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "RedHat"
      notify: 
        - Copy file for httpd
        - Start httpd service

    - name: Installing apache2 package on Debian
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"
      notify: 
        - Copy file for apache2
        - Start apache2 service

  handlers:
    - name: Copy file for httpd
      copy:
        src: /home/ansadmin/index.html
        dest: /var/www/html/
      when: ansible_os_family == "RedHat"

    - name: Start httpd service
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"

    - name: Copy file for apache2
      copy:
        src: /home/ansadmin/index.html
        dest: /var/www/html/
      when: ansible_os_family == "Debian"

    - name: Start apache2 service
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

