---
- name: this playbook install multiple packages
  hosts: metro
  become: true
  tasks:
  - name: installing packages
    yum:
      name: ['git', 'make', 'gcc', 'mysql', 'tree', 'which', 'docker',]
      state: installed
